version: '3'

services:
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'

  web:
    build: ./django
    volumes:
      - .:/app
    entrypoint: scripts/wait-for-it.sh db:5432 -- /bin/sh scripts/init.sh
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:1.19.0-alpine

    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - /root/ssl/:/etc/nginx/ssl
      - ./django/static/:/usr/share/nginx/html/static
    ports:
      - 80:80
    depends_on:
      - web
