version: '3'

services:
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    restart: always

  ap:
    # djangoフォルダ内のDockerfileから起動
    build: ./django
    volumes:
      - ./django:/app
    # staticファイルをstaticfilesに収集
    command: python manage.py collectstatic --noinput
    # dbが利用可能になるまで待機してから、init.shを実行
    entrypoint: /bin/sh scripts/init.dev.sh
    expose:
      # nginxと通信するためのポートを解放
      - 8000
    depends_on:
      - db
    restart:
      always

  web:
    # reactフォルダ内のDockerfileから起動
    build: ./react
    volumes:
      - ./react:/usr/app
    ports:
      - "3000:3000"
    restart: always
    tty: true

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl.dev:/etc/nginx/ssl
      - ./django/staticfiles/:/usr/share/nginx/html/static
    depends_on:
      - ap
