version: '3'

services:
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    restart: always

  ap:
    build: ./django
    volumes:
      - ./django:/app
    command: python manage.py collectstatic --noinput
    entrypoint: scripts/wait-for-it.sh db:5432 -- /bin/sh scripts/init.sh
    expose:
      - 8000
    depends_on:
      - db
    restart: always

  web:
    build: ./react
    volumes:
      - ./react:/usr/app
    restart: always
    command: /bin/sh -c 'npm install && npm run build'

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      # SSL証明書、公開鍵、秘密鍵を配置
      - /etc/letsencrypt/files/votify.jp:/etc/nginx/ssl
      # バックエンドの静的ファイルを配置する
      - ./django/staticfiles/:/usr/share/nginx/html/static
      # フロントエンドのビルド済ファイルを配置する
      - ./react/build/:/usr/share/nginx/html/build
    ports:
      - 443:443
      - 80:80
    depends_on:
      - ap
    restart: always
