version: '3'

services:
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    restart: always

  web:
    # djangoフォルダ内のDockerfileから起動
    build: ./django
    volumes:
      - ./django:/app
    # staticファイルをstaticfilesに収集
    command: python manage.py collectstatic --noinput
    # dbが利用可能になるまで待機してから、init.shを実行
    entrypoint: scripts/wait-for-it.sh db:5432 -- /bin/sh scripts/init.sh
    expose:
      # nginxと通信するためのポートを解放
      - 8000
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      # nginx.confを配置
      - ./nginx/conf.d:/etc/nginx/conf.d
      # SSL証明書、公開鍵、秘密鍵を配置
      - ./nginx/ssl:/etc/nginx/ssl
      # 静的ファイルを配置する
      - ./django/staticfiles/:/usr/share/nginx/html/static
    ports:
      # https通信用ポート解放
      - 443:443
      # http通信用ポート解放
      - 80:80
    depends_on:
      - web
    restart: always
