# Generated by Django 3.2.9 on 2022-04-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(default='no_image.png', upload_to='uploads/profile_images/'),
        ),
    ]
