# Generated by Django 3.2.9 on 2022-04-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_account_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(default='uploads/profile_images/no_image.png', upload_to='uploads/profile_images/'),
        ),
    ]
