# Generated by Django 3.2.9 on 2022-05-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_account_account_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='watched',
            field=models.IntegerField(default=0),
        ),
    ]
