# Generated by Django 3.2.9 on 2022-05-12 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_question_watched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_image',
        ),
    ]
