# Generated by Django 3.2.9 on 2022-05-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_rename_question_text_question_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
