# Generated by Django 3.2.9 on 2022-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20220523_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
