# Generated by Django 3.2.9 on 2022-06-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_vote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
