# Generated by Django 3.2.9 on 2022-06-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_remove_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
