# Generated by Django 3.2.9 on 2022-07-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20220630_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(max_length=200),
        ),
    ]
