version: 2
 
jobs:
    # EC2にソースをアップロードする
    ec2-deploy:
        docker:
            - image: cimg/base:2023.03
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            - run: ssh ${USER_NAME}@${HOST_NAME} -o "StrictHostKeyChecking no" 'cd votify && sudo git stash && sudo docker system prune -f && sudo git pull && sudo docker-compose up -d --build'
 
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - ec2-deploy
