version: 2
 
jobs:
    build:
        docker:
            - image: alpine
        steps:
            - run: yum install -y git
            - checkout
            - run:
                name: Echo Test
                command: echo "CircleCI Test"
    deploy:
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            # CircleCI に登録した秘密鍵を呼び出す
            - add_ssh_keys:
            - run: ssh ${USER_NAME}@${HOST_NAME} 'sudo su && cd votify && git stash && git pull && docker-compose up -d --build'
 
workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
