# Generated by Django 3.2.9 on 2022-02-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220210_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecontent',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
